language: node_js
node_js:
 - "0.10"

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - npm install -g bower grunt-cli@0.1.x
 - npm install --quiet
 - bower cache clean
 - bower install --verbose

script: grunt karma:unit
